### ISSUE TITLE
Crash with enhanced celestials because it updated 1.20.1

### ISSUE THREAD

**Issue by Poopchungus** [Povstalec/StellarView#47]
Game crashes with enhanced celestials in it because enhanced celestials recently updated

Suspected Mod: 
	Stellar View (stellarview), Version: 0.3.3
		Issue tracker URL: https://github.com/Povstalec/StellarView/issues
		at TRANSFORMER/stellarview@0.3.3/net.povstalec.stellarview.compatibility.enhancedcelestials.EnhancedCelestialsCompatibility.getMoonColor(EnhancedCelestialsCompatibility.java:41)
Stacktrace:
	at net.povstalec.stellarview.compatibility.enhancedcelestials.EnhancedCelestialsCompatibility.getMoonColor(EnhancedCelestialsCompatibility.java:41) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.Moon.moonRGBA(Moon.java:77) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.Moon.renderTextureLayer(Moon.java:91) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.TexturedObject.renderTextureLayers(TexturedObject.java:127) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.TexturedObject.render(TexturedObject.java:161) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.TexturedObject.render(TexturedObject.java:155) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.TexturedObject.render(TexturedObject.java:169) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.Space.render(Space.java:93) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.ViewCenter.renderSkyObjects(ViewCenter.java:330) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.SpaceObject.renderFrom(SpaceObject.java:209) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.objects.SpaceObject.renderFrom(SpaceObject.java:207) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.ViewCenter.renderSkyObjectsFrom(ViewCenter.java:318) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.ViewCenter.renderSky(ViewCenter.java:372) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.resourcepack.ViewCenters.renderViewCenterSky(ViewCenters.java:46) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.render.level.StellarViewOverworldEffects.renderSky(StellarViewOverworldEffects.java:28) ~[Stellar%20View-1.20.1-0.3.3.jar%23974!/:0.3.3] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_202423_(LevelRenderer.java:1774) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin from mod alexscaves,pl:mixin:APP:ryoamiclights.common.mixins.json:CommonWorldRendererMixin from mod ryoamiclights,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin from mod embeddium,pl:mixin:APP:sleep_tight-common.mixins.json:LevelRendererMixin from mod sleep_tight,pl:mixin:APP:mixins.essential.json:feature.cosmetics.Mixin_UpdateCosmetics from mod (unknown),pl:mixin:APP:notenoughanimations.mixins.json:LevelRendererMixin from mod notenoughanimations,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor from mod flywheel,pl:mixin:APP:flywheel.mixins.json:fix.FixFabulousDepthMixin from mod flywheel,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceUpdateMixin from mod flywheel,pl:mixin:APP:mixins.satin.client.json:blockrenderlayer.WorldRendererMixin from mod satin,pl:mixin:APP:mixins.satin.client.json:event.WorldRendererMixin from mod satin,pl:mixin:APP:particle_core.mixins.json:WorldRendererDecreaseMixin from mod particle_core,pl:mixin:APP:particle_core.mixins.json:WorldRendererTypeMixin from mod particle_core,pl:mixin:APP:enhancedblockentities.mixins.json:WorldRendererMixin from mod enhancedblockentities,pl:mixin:APP:fabric-resource-loader-v0.client.mixins.json:KeyedResourceReloadListenerClientMixin from mod fabric_resource_loader_v0,pl:mixin:APP:lodestone.mixins.json:WorldRendererMixin from mod lodestone,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LevelRendererMixin from mod playeranimator,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin from mod supermartijn642corelib,pl:mixin:APP:fabric-rendering-v1.mixins.json:WorldRendererMixin from mod fabric_rendering_v1,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer from mod sereneseasons,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin from mod entityculling,pl:mixin:APP:blue_skies.mixins.json:LevelRendererMixin from mod blue_skies,pl:mixin:APP:aether.mixins.json:client.accessor.LevelRendererAccessor from mod aether,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin from mod citadel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer from mod enhancedcelestials,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer from mod patchouli,pl:mixin:APP:biomemakeover-common.mixins.json:client.LevelRendererMixin from mod biomemakeover,pl:mixin:APP:forge-sfcr-common.mixins.json:WorldRendererMixin from mod (unknown),pl:mixin:APP:quark.mixins.json:client.LevelRendererMixin from mod quark,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin from mod supplementaries,pl:mixin:APP:supplementaries.mixins.json:LevelRendererMixin from mod supplementaries,pl:mixin:APP:create.mixins.json:client.LevelRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin from mod embeddium,pl:mixin:APP:lucent.mixins.json:LevelRendererMixin from mod lucent,pl:mixin:APP:lucent.mixins.json:LevelRendererMixinThreadedRendering from mod lucent,pl:mixin:APP:flywheel.mixins.json:LevelRendererMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1155) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:APP:alexscaves.mixins.json:client.LevelRendererMixin from mod alexscaves,pl:mixin:APP:ryoamiclights.common.mixins.json:CommonWorldRendererMixin from mod ryoamiclights,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin from mod embeddium,pl:mixin:APP:sleep_tight-common.mixins.json:LevelRendererMixin from mod sleep_tight,pl:mixin:APP:mixins.essential.json:feature.cosmetics.Mixin_UpdateCosmetics from mod (unknown),pl:mixin:APP:notenoughanimations.mixins.json:LevelRendererMixin from mod notenoughanimations,pl:mixin:APP:flywheel.mixins.json:LevelRendererAccessor from mod flywheel,pl:mixin:APP:flywheel.mixins.json:fix.FixFabulousDepthMixin from mod flywheel,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceUpdateMixin from mod flywheel,pl:mixin:APP:mixins.satin.client.json:blockrenderlayer.WorldRendererMixin from mod satin,pl:mixin:APP:mixins.satin.client.json:event.WorldRendererMixin from mod satin,pl:mixin:APP:particle_core.mixins.json:WorldRendererDecreaseMixin from mod particle_core,pl:mixin:APP:particle_core.mixins.json:WorldRendererTypeMixin from mod particle_core,pl:mixin:APP:enhancedblockentities.mixins.json:WorldRendererMixin from mod enhancedblockentities,pl:mixin:APP:fabric-resource-loader-v0.client.mixins.json:KeyedResourceReloadListenerClientMixin from mod fabric_resource_loader_v0,pl:mixin:APP:lodestone.mixins.json:WorldRendererMixin from mod lodestone,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LevelRendererMixin from mod playeranimator,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin from mod supermartijn642corelib,pl:mixin:APP:fabric-rendering-v1.mixins.json:WorldRendererMixin from mod fabric_rendering_v1,pl:mixin:APP:sereneseasons.mixins.json:client.MixinLevelRenderer from mod sereneseasons,pl:mixin:APP:entityculling.mixins.json:WorldRendererMixin from mod entityculling,pl:mixin:APP:blue_skies.mixins.json:LevelRendererMixin from mod blue_skies,pl:mixin:APP:aether.mixins.json:client.accessor.LevelRendererAccessor from mod aether,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin from mod citadel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinWorldRenderer from mod enhancedcelestials,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer from mod patchouli,pl:mixin:APP:biomemakeover-common.mixins.json:client.LevelRendererMixin from mod biomemakeover,pl:mixin:APP:forge-sfcr-common.mixins.json:WorldRendererMixin from mod (unknown),pl:mixin:APP:quark.mixins.json:client.LevelRendererMixin from mod quark,pl:mixin:APP:supplementaries-common.mixins.json:LevelRendererMixin from mod supplementaries,pl:mixin:APP:supplementaries.mixins.json:LevelRendererMixin from mod supplementaries,pl:mixin:APP:create.mixins.json:client.LevelRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin from mod embeddium,pl:mixin:APP:lucent.mixins.json:LevelRendererMixin from mod lucent,pl:mixin:APP:lucent.mixins.json:LevelRendererMixinThreadedRendering from mod lucent,pl:mixin:APP:flywheel.mixins.json:LevelRendererMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:sleep_tight-common.mixins.json:GameRendererMixin from mod sleep_tight,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority_Pre from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin from mod satin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:AdditionalAdditions.mixins.json:GameRendererMixin from mod additionaladditions,pl:mixin:APP:lodestone.mixins.json:GameRendererMixin from mod lodestone,pl:mixin:APP:mixins.sodiumextras.json:impl.darkness.GameRendererMixin from mod sodiumextras,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:cold_sweat.mixin.json:MixinAfterLevelRender from mod cold_sweat,pl:mixin:APP:forge-sfcr-common.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:crackerslib.mixins.json:MixinGameRendererAccessor from mod crackerslib,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Affected level --

**Comment by Poopchungus** [comment]
mmmmmmmmmmmmmm

**Comment by Noobly-Walker** [comment]
This will likely be fixed in the next patch. Povstalec is just busy with other things at this time.

**Comment by MaxWasUnavailable** [comment]
Can confirm I'm having the same crash.

```
java.lang.NoSuchMethodError: 'net.minecraft.core.Holder corgitaco.enhancedcelestials.lunarevent.LunarForecast.getMostRecentEvent()'
	at net.povstalec.stellarview.compatibility.enhancedcelestials.EnhancedCelestialsCompatibility.adjustLightmapColors(EnhancedCelestialsCompatibility.java:87) ~[Stellar%20View-1.20.1-0.3.3.jar%23878!/:0.3.3] {re:classloading}
	at net.povstalec.stellarview.client.render.level.StellarViewOverworldEffects.adjustLightmapColors(StellarViewOverworldEffects.java:41) ~[Stellar%20View-1.20.1-0.3.3.jar%23878!/:0.3.3] {re:classloading}
	at net.minecraft.client.renderer.LightTexture.handler$hph000$ac_updateLightTexture(LightTexture.java:659) ~[client-1.20.1-20230612.114412-srg.jar%23938!/:?] 
```
